### ISSUE TITLE
Version 1.8.3 server will crash if joined in the world

### ISSUE THREAD

**Issue by SavageNeo1** [The-Nexus-Project/Limitless-3#75] opened 2021-01-04 07:39 UTC
### Describe your issue, what happened?
Everytime I try to join the server, the server crashes with no crash log. Also reverted to 1.8.2 and the server worked pretty well.

### To Reproduce

1. Start the server and wait until it is started
2. Click "Join Server" on minecraft
3. Wait
4. Your minecraft will crash on the loading screen and so will the server.

### Expected behavior
I expected it to be a bug and tried again for a hour and did not work.

### Affected Version

- Pack Version: 1.8.3
- On a server?: 1.8.3

**Comment by Gbergz** [comment] 2021-01-04 11:55
Probably duplicate of #74

**Closed as completed by Gbergz** 2021-01-04 11:55 UTC
