### ISSUE TITLE
Most modded trees/other modded blocks become ghost blocks on server

### ISSUE THREAD

**Issue by AzeznLadyofFloof** [The-Nexus-Project/Limitless-3#247] opened 2022-01-09 13:41 UTC
### Describe your issue, what happened?
Most modded trees grow into ghost blocks on server. loading and unloading the chunk fixes it, but it's happening for all my players Also other blocks do the same thing, modded doors and RFtools shield projector blocks. 

### To Reproduce
1. Open a server, go creative and plant a maple sapling
2. Grow it with bonemeal/wait
3. Trees spawn as one or two visible blocks the rest being ghosts

### Expected behavior
Trees/other blocks would show for as full blocks

### Crash Reports & Logs (Don't paste entire crash reports here.)
Spams this:
[net.minecraft.server.management.PlayerInteractionManager/]: Mismatch in destroy block pos: BlockPos{x=0, y=0, z=0} BlockPos{x=-224, y=68, z=-245}

### Affected Version
-1.16.5
-Limitless-3-1.11.7.zip
-On a server?: Yes

**Comment by Gbergz** [comment] 2022-01-09 13:42
If this is in a Claimed Chunk, you might need to add the Rftools blocks etc as an ally.

**Comment by AzeznLadyofFloof** [comment] 2022-01-10 09:50
> If this is in a Claimed Chunk, you might need to add the Rftools blocks etc as an ally.

It's not, i thought that too, but still having shield/tree bugs

**Comment by Gbergz** [comment] 2022-01-10 09:53
Huh, weird! Well I've never experienced this myself. Sounds really annoying.. And usually it is caused by the chunk claims (reports by other uses).

hm..

**Comment by AzeznLadyofFloof** [comment] 2022-01-12 10:20
> Huh, weird! Well I've never experienced this myself. Sounds really annoying.. And usually it is caused by the chunk claims (reports by other uses).
> 
> hm..

So i made a new server. 100% fresh... still happens, same with all 5 of my players. It's only on multiplayer too

**Comment by Gbergz** [comment] 2022-01-12 10:45
Hm, looks like Enigmatica 6 is also having this issue.

But;
Can you try hitting the AntiGhost keybind to see if they reappear?

**Comment by Gbergz** [comment] 2022-01-12 10:52
Might be a conflict on "g" by default, but changing it to a nonconflict bind should allow you to see the ghost blocks again.

Might need to click it multiple times.

**Comment by Gbergz** [comment] 2022-01-12 10:58
In my testings it seems to only affect Atmospheric, Environmental, Pam's, DruidCraft & Ars Nouveau Saplings.
Pretty annoying, but the AntiGhost mod does help refreshing the blocks. Since it's a desync issue.

**Comment by DontCareIfHacked** [comment] 2022-01-14 07:16
This also happens when construction wands are used to place non-minecraft blocks, such as tinker's construct version of glass. Therefor, I don't think the issue is with ally.

**Comment by AzeznLadyofFloof** [comment] 2022-01-15 09:59
> In my testings it seems to only affect Atmospheric, Environmental, Pam's, DruidCraft & Ars Nouveau Saplings. Pretty annoying, but the AntiGhost mod does help refreshing the blocks. Since it's a desync issue.

Indeed, it's very weird. and yea Same thing here

**Comment by Gbergz** [comment] 2022-01-24 16:18
Next update might fix this. In my testings it doesn't occur anymore. Hopefully it's not a onetime deal. And it is fixed.

**Comment by AzeznLadyofFloof** [comment] 2022-01-24 23:20
> Next update might fix this. In my testings it doesn't occur anymore. Hopefully it's not a onetime deal. And it is fixed.

Hope so, ill check soon!

**Comment by DontCareIfHacked** [comment] 2022-01-25 08:11
Hopefully the next release doesn't break villager's ability to restock like it did from 1.16.5 --> 1.16.5hf. That was.... interesting.... trying to fix.

**Comment by AzeznLadyofFloof** [comment] 2022-01-27 02:08
I am happy to confirm, maple trees work! Thanks so much ^w^

**Comment by Gbergz** [comment] 2022-01-27 09:08
Awesome ! :)
Closing now.

**Closed as completed by Gbergz** 2022-01-27 09:08 UTC
Labels: bug, fixed next release
