### ISSUE TITLE
No ores spawning in 1.0.0 Beta

### ISSUE THREAD

**Issue by thetzeestraten** [The-Nexus-Project/Limitless-3#5] opened 2020-09-17 02:29 UTC
Running the beta modpack currently, I've run into an issue where no ores are being generated in the world.

Version deets:

TNP 3 Version: 1.0.0 (beta)
Minecraft Version: 1.16.2
(modded) forge-33.0.37

**Comment by thetzeestraten** [comment] 2020-09-17 05:33
Update: I disabled many of the mods that I figured I wouldn't use, need or were redundant with another mod, to see if I could lighten the mod pack, and added Mana and Artifice.

The ore now was generated in the world, meaning I must have disable the mod that messed it up. I'm in no mood to go and try them all to narrow down the culprit/s, so I'll just upload my twitch mod profile that is functional as of 17/09/20.

[TNP Custom (1)-1.0.0.zip](https://github.com/The-Nexus-Project/Limitless-3/files/5236550/TNP.Custom.1.-1.0.0.zip)

**Comment by Gbergz** [comment] 2020-09-17 13:49
This is caused by the mod BYG ”Oh The Biomes You’ll Go” its removed if not fixed in the next update. Which will release asap, when Twitch adds 1.16.3 support.

EDIT: This might be a conflict with BYG and some other mods. Ores and other worldgen features still works when using BYG on a clean instance .

**Closed as completed** 2020-09-19 14:39 UTC
Labels: fixed indev
