### ISSUE TITLE
Continuous server crashes

### ISSUE THREAD

**Issue by babynicol3** [The-Nexus-Project/Limitless-3#31] opened 2020-11-14 22:35 UTC
Mod: Possibly pneumaticcraft

Optifine: not used

Issue: Server randomly freezes, makes players wait 180 seconds before any update in the console appears, and then the server is forcibly shutdown.

Reproduce:
1. Doing anything
2. Notice can't hit/open anything
3. Wait 180 seconds
4. See error/logs

### Crash Reports & Logs 
https://pastebin.com/VT4eXXAi

### Affected Version
- Pack Version: 1.7.2a
- On a server?: My own server

**Comment by noncom** [comment] 2020-11-16 10:29
Probably this is not related to Pneumatic Craft, to check this try removing the mod and seeing if the problem persists.

Is this happening right after you start the server/first join?
Have you tried re-creating the world?

I've actually seen this myself a lot of times, and not only with this modpack. One possibility could be the worldgen issue in vanilla 1.16.3 that's fixed in 1.16.4. Or it might be some mod. Or it's the 1.16.3 issue + mod.

If the issue is 100% reproducible then to find which mod could be causing it you need to remove a half of them and see if the problem is still there. Keep removing or adding the remaining mods in halves until you converge on the exact one that causes it. Then confirm that it's exactly that mod by an additional check -- leave this mod enabled and remove all else. I was hunting for this bug myself for quite a while already as well, but unfortunately it does not repeat for me these days.

**Comment by MokahTGS** [comment] 2020-11-19 16:55
The other thing that I have done in the past is turn off the watchdog in the server properties.  Your crash log is referencing the Watchdog on the server which watches for lagging tick times.  On a modded server, it tends to freak out.  There is a line for Max Tick Time that you can put -1 to turn it off.  That has stopped crashes for us in the past.

**Closed as completed** 2020-11-25 14:31 UTC
