### ISSUE TITLE
FTB Quest Task Progress resetting on every world load

### ISSUE THREAD

**Issue by GarthF** [The-Nexus-Project/Limitless-3#24] opened 2020-11-03 12:46 UTC
### Describe your issue, what happened?
On every load into my world, FTB Quest task progress is being reset. Claimed rewards are remembered, but all quest progress is reset. Created a blank new world, same issue.

### To Reproduce
1. Complete some of the quests (punch wood or tick one of the welcome quests)
2. Exit Minecraft
3. Player FTB Quest .snbt has some tasks listed as completed under task_progress
4. Reload world. As world loads, the player .snbt updates and all task progress is removed.

### Expected behavior
Quest progress should be remembered between loads.

### Screenshots
![image](https://user-images.githubusercontent.com/13380578/97986990-393cce00-1de3-11eb-9eb1-043913259315.png)

### Affected Version
- Pack Version: v1.7.1
- On a server?: No

**Comment by Gbergz** [comment] 2020-11-03 13:05
Hey, yes this is a known issue. Existing worlds with quests-progress seems to have been reset due to some changes in the mod?, nothing I can do about this unfortunately. Sorry! (That is if it isnt a bug in the mod ofcourse.)

Though, regarding your issue- only the **Welcome** Chapter seems to reset on every world load due to the tasks being locked behind a quest activation line.. (perhaps a bug in the mod?) 

I just tested it and only the quest completed "Toasts" show up and quests doesn't actually get reset every world load / relog to server.

**-** Gbergz

**Comment by GarthF** [comment] 2020-11-03 13:14
I tested it with the punch wood quest, and if I have wood in my inventory on load, it checks off the quest. If I don't have wood in my inventory, the quest resets to incomplete.

**Comment by GarthF** [comment] 2020-11-03 13:43
Problem went away when I rolled back to ftb-quests-1603.1.0.5, so it seems like it is a mod issue.

**Comment by Gbergz** [comment] 2020-11-03 13:45
Was just about to comment this, downgraded to 1.0.5 and the problem is gone.

**Comment by Gbergz** [comment] 2020-11-03 14:13
Just reverted FTB Quests back to 1.0.5 and posted a pack update: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3100973

Closing this now.

**Closed as completed by Gbergz** 2020-11-03 14:13 UTC
Labels: known issue
