### ISSUE TITLE
Time in a bottle

### ISSUE THREAD

**Issue by QueenMissy** [The-Nexus-Project/Limitless-3#138] opened 2021-03-02 13:47 UTC
Time in a Bottle only stores time if it is in your offhand then stops when its in your actual inventory. Not sure if you have changed its config as i have never had it stop in the inventory before.

**Comment by Gbergz** [comment] 2021-03-02 13:49
It just doesn't update while in inventory, it does work though. Did my testings. Take it out then place it in inventory again.

**Comment by QueenMissy** [comment] 2021-03-02 14:23
I did that numerous times. It does tend to stop though if you move it and then restarts in the off hand. having used it before elsewhere i have never had it stop in the inventory once,

**Comment by Gbergz** [comment] 2021-03-02 14:35
cant reproduce your issue in my instance, it counts time just fine. Just doesnt update in realtime while hovering over it.

**Comment by Gbergz** [comment] 2021-03-02 14:37
But if you feel like it doesnt actually work like it should, open an issue on their issue tracker
https://github.com/haoict/time-in-a-bottle/issues

**Comment by QueenMissy** [comment] 2021-03-02 14:57
That i will. Even just to see what they have to say in regards to it.

**Comment by Gbergz** [comment] 2021-03-02 20:03
Closing this then.

**Closed as completed by Gbergz** 2021-03-02 20:03 UTC
